server:
  port: 8000

spring:
  application:
    name: ucla-discovery

eureka:
  instance:
    hostname: ucla-discovery
    registry:
      default-open-for-traffic-count: 1 # If set to 0, server replication can be activated (default 1)
  client:
    registerWithEureka: false # Whether to register itself in the registry (default true)
    fetchRegistry: false # Whether to fetch information from the registry (default true), Eureka Client checks for registry changes every 30 seconds
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  # Renews Threshold => Number of heartbeats per minute (default 30 seconds) * Number of instances + Minimum number of instances configured by Spring (1) * Rounded renewal-percent-threshold value.
  # ex: 2 * 1 + 1 * 0.85 = 3
  # Renews (last min) => Number of heartbeats per minute (default 30 seconds) * Number of instances
  # ex: 2 * 1 = 2
  server:
    renewal-percent-threshold: 0 # This value is used to calculate the expected number of heartbeats per minute
    enable-self-preservation: true # Self-preservation mode to prevent service deregistration due to temporary network issues (recommended true for production)

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
