apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucla-file-manage-service
  labels:
    app: ucla-file-manage-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ucla-file-manage-service
  template:
    metadata:
      labels:
        app: ucla-file-manage-service
    spec:
      containers:
        - name: ucla-file-manage-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: file-storage
              mountPath: /videos
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-storage-pvc