apiVersion: v1
kind: Service
metadata:
  name: ucla-discovery
  labels:
    app: ucla-discovery
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ucla-discovery